version: "3.9"
services:
  react:
    build: 
      context: ./react
      dockerfile: Dockerfile
    image: react
    container_name: front
    ports:
      - "80:80"
    depends_on: 
      - node
    networks: 
      - app-network
  node: 
    build: 
      context: ./node
      dockerfile: Dockerfile
    image: node
    container_name: backend
    restart: unless-stopped
    env_file: ./node/.env
    ports:
      - "3000:3000"
    networks: 
      - app-network

networks: 
  app-network:
    driver: bridge
